import{a as L,S as b,i as f}from"./assets/vendor-56bcefdc.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const w="44071791-e24b31a34b7a75e1ae02e9c2e",v="https://pixabay.com/api/";async function h(e,a=1){const s=await L.get(`${v}`,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}});if(s.status!==200)throw new Error("Failed to fetch images");return s.data}let d;function y(e,a){const s=document.querySelector(".gallery"),n=s.clientHeight;a&&(s.innerHTML=""),s.innerHTML+=e.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>`).join(""),d?d.refresh():d=new b(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});const o=s.clientHeight;window.scrollBy({top:o-n,behavior:"smooth"})}function l(e){f.error({title:"Error",message:e,position:"topRight"})}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function p(){console.log("-"),setTimeout(()=>{document.querySelector(".div-loader").classList.add("hidden")},2e3)}function u(e){const a=document.querySelector(".load-more");e?a.classList.remove("hidden"):a.classList.add("hidden")}let i=1,g="";document.querySelector("#search-form").addEventListener("submit",async e=>{e.preventDefault();const a=e.target.elements.searchQuery.value.trim();if(!a){l("Please enter a search query");return}g=a,i=1,q(),u(!1),m();try{const s=await h(a);s.hits.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(y(s.hits,!0),u(s.totalHits>i*15))}catch(s){l(s.message)}finally{p()}});document.querySelector(".load-more").addEventListener("click",async()=>{i+=1,m();try{const e=await h(g,i);y(e.hits,!1),u(e.totalHits>i*15),e.totalHits<=i*15&&f.info({title:"info",message:"Weare sorry, but you`ve reached the end of search result.",position:"topRight"})}catch(e){l(e.message)}finally{p()}});t;
//# sourceMappingURL=commonHelpers.js.map
